#!/bin/bash
# Install useful utilities
#
pushd "$(dirname $0)" > /dev/null
  ./jq-install
  ./httpie-install 

  ./kubebox-install
  ./kubetail-install
  ./kubectx-install
  ./config-bash-autocomplete.sh

popd > /bin/bash