#!/bin/bash
# Ref: https://github.com/mikefarah/yq
if [ ! -e /usr/local/bin/yq ]; then
  wget https://github.com/mikefarah/yq/releases/download/v4.11.2/yq_linux_amd64.tar.gz -O  - |\
  sudo tar xz && sudo mv yq_linux_amd64 /usr/local/bin/yq
fi

