#!/bin/bash
#  Install Go on Ubuntu
#
#
set -eu
GO_VERSION=${GO_VERSION:="1.20"}
pushd /tmp > /dev/null
    wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
    sudo tar -xvf go1.16.4.linux-amd64.tar.gz 
    sudo mv go /usr/local  

    fi
    if ! grep -q "GOPATH/bin" ~/.profile; then
      echo "export PATH=$GOPATH/bin:$GOROOT/bin:$PATH" >> ~/.profile
    fi
popd > /dev/null 